from django.urls import path

from .views import (
    AskAIView,
    AIChatHistoryListView,
    AIChatHistoryDetailView,
    AssignTagsToChatSessionView,
    BulkArchiveChatSessionsView,
    BulkClearSessionMessagesView,
    BulkDeleteChatMessagesView,
    BulkImportantChatMessagesView,
    BulkPermanentDeleteChatSessionsView,
    BulkPinChatSessionsView,
    ChatSessionListCreateView,
    ChatSessionDetailView,
    ChatSessionTagDetailView,
    ChatSessionTagListCreateView,
    ChatSessionsByTagView,
    CopyChatMessagesView,
    DocumentChunksPreviewView,
    EmptyTrashChatSessionsView,
    MergeChatSessionsView,
    RAGSourceDocumentDetailView,
    RebuildSingleDocumentView,
    SendSessionMessageView,
    BuildKnowledgeBaseView,
    AskRAGView,
    KnowledgeDocumentListCreateView,
    KnowledgeDocumentDetailView,
    SendSessionRAGMessageView,
    StreamSessionRAGMessageView,
    LocalModelListView,
    AIHealthCheckView,
    AIUsageLogListView,
    AIDashboardSummaryView,
    AIRecentActivityView,
    ClearAIChatHistoryView,
    ClearKnowledgeDocumentsView,
    ClearAIUsageLogsView,
    ChatMessageDetailView,
    RegenerateChatMessageView,
    RegenerateRAGChatMessageView,
    ExportChatSessionTXTView,
    ExportChatSessionJSONView,
    KnowledgeBaseStatusView,
    TogglePinChatSessionView,
    ToggleArchiveChatSessionView,
    TrashChatSessionListView,
    RestoreChatSessionView,
    PermanentDeleteChatSessionView,
    StreamSessionMessageView,
    ChatSessionStatsView,
    DuplicateChatSessionView,
    SearchChatSessionMessagesView,
    ToggleImportantChatMessageView,
    ImportantChatMessagesListView,
    ChatSessionTimelineView,
    ChatSessionPreviewView,
    BulkSoftDeleteChatSessionsView,
    BulkRestoreChatSessionsView,
)
from .views import StreamAIView
urlpatterns = [
    path("ask/", AskAIView.as_view(), name="ask-ai"),

    path("history/", AIChatHistoryListView.as_view(), name="ai-chat-history"),
    path("history/<int:pk>/", AIChatHistoryDetailView.as_view(), name="ai-chat-detail"),

    path("sessions/", ChatSessionListCreateView.as_view(), name="chat-session-list-create"),
    path("sessions/<int:pk>/", ChatSessionDetailView.as_view(), name="chat-session-detail"),
    path("sessions/<int:pk>/messages/", SendSessionMessageView.as_view(), name="send-session-message"),
    path(
        "stream/",
        StreamAIView.as_view(),
        name="stream-ai",
    ),
    path("rag/build/", BuildKnowledgeBaseView.as_view(), name="rag-build"),
    path("rag/ask/", AskRAGView.as_view(), name="rag-ask"),
    path("documents/", KnowledgeDocumentListCreateView.as_view(), name="knowledge-documents"),
    path("documents/<int:pk>/", KnowledgeDocumentDetailView.as_view(), name="knowledge-document-detail"),
    path(
        "sessions/<int:pk>/rag-message/",
        SendSessionRAGMessageView.as_view(),
        name="send-session-rag-message",
    ),
    path(
        "sessions/<int:pk>/rag-stream/",
        StreamSessionRAGMessageView.as_view(),
        name="stream-session-rag-message",
    ),
    path("models/", LocalModelListView.as_view(), name="local-model-list"),
    path("health/", AIHealthCheckView.as_view(), name="ai-health-check"),
    path("usage-logs/", AIUsageLogListView.as_view(), name="ai-usage-logs"),
    path("dashboard/summary/", AIDashboardSummaryView.as_view(), name="ai-dashboard-summary"),
    path("dashboard/recent-activity/", AIRecentActivityView.as_view(), name="ai-recent-activity"),
    path(
        "history/clear/",
        ClearAIChatHistoryView.as_view(),
        name="clear-ai-chat-history",
    ),
    path(
        "documents/clear/",
        ClearKnowledgeDocumentsView.as_view(),
        name="clear-knowledge-documents",
    ),
    path(
        "usage-logs/clear/",
        ClearAIUsageLogsView.as_view(),
        name="clear-ai-usage-logs",
    ),
    path(
        "sessions/<int:session_pk>/messages/<int:message_pk>/",
        ChatMessageDetailView.as_view(),
        name="chat-message-detail",
    ),
    path(
        "sessions/<int:session_pk>/messages/<int:message_pk>/regenerate/",
        RegenerateChatMessageView.as_view(),
        name="regenerate-chat-message",
    ),
    path(
        "sessions/<int:session_pk>/messages/<int:message_pk>/regenerate-rag/",
        RegenerateRAGChatMessageView.as_view(),
        name="regenerate-rag-chat-message",
    ),
    path(
        "sessions/<int:pk>/export-txt/",
        ExportChatSessionTXTView.as_view(),
        name="export-chat-session-txt",
    ),
    path(
        "sessions/<int:pk>/export-json/",
        ExportChatSessionJSONView.as_view(),
        name="export-chat-session-json",
    ),
    path(
        "rag/status/",
        KnowledgeBaseStatusView.as_view(),
        name="rag-status",
    ),
    path(
        "sessions/<int:pk>/toggle-pin/",
        TogglePinChatSessionView.as_view(),
        name="toggle-pin-chat-session",
    ),
    path(
        "sessions/<int:pk>/toggle-archive/",
        ToggleArchiveChatSessionView.as_view(),
        name="toggle-archive-chat-session",
    ),
    path(
        "sessions/trash/",
        TrashChatSessionListView.as_view(),
        name="trash-chat-sessions",
    ),
    path(
        "sessions/<int:pk>/restore/",
        RestoreChatSessionView.as_view(),
        name="restore-chat-session",
    ),
    path(
        "sessions/<int:pk>/permanent-delete/",
        PermanentDeleteChatSessionView.as_view(),
        name="permanent-delete-chat-session",
    ),
    path(
        "sessions/<int:pk>/stream-message/",
        StreamSessionMessageView.as_view(),
        name="stream-session-message",
    ),
    path(
        "sessions/<int:pk>/stats/",
        ChatSessionStatsView.as_view(),
        name="chat-session-stats",
    ),
    path(
        "sessions/<int:pk>/duplicate/",
        DuplicateChatSessionView.as_view(),
        name="duplicate-chat-session",
    ),
    path(
        "sessions/<int:pk>/search-messages/",
        SearchChatSessionMessagesView.as_view(),
        name="search-chat-session-messages",
    ),
    path(
        "sessions/<int:session_pk>/messages/<int:message_pk>/toggle-important/",
        ToggleImportantChatMessageView.as_view(),
        name="toggle-important-chat-message",
    ),
    path(
        "important-messages/",
        ImportantChatMessagesListView.as_view(),
        name="important-chat-messages",
    ),
    path(
        "sessions/<int:pk>/timeline/",
        ChatSessionTimelineView.as_view(),
        name="chat-session-timeline",
    ),
    path(
        "sessions/<int:pk>/preview/",
        ChatSessionPreviewView.as_view(),
        name="chat-session-preview",
    ),
    path(
        "sessions/bulk-delete/",
        BulkSoftDeleteChatSessionsView.as_view(),
        name="bulk-delete-chat-sessions",
    ),
    path(
        "sessions/bulk-restore/",
        BulkRestoreChatSessionsView.as_view(),
        name="bulk-restore-chat-sessions",
    ),
    path(
        "sessions/bulk-permanent-delete/",
        BulkPermanentDeleteChatSessionsView.as_view(),
        name="bulk-permanent-delete-chat-sessions",
    ),
    path(
        "sessions/trash/empty/",
        EmptyTrashChatSessionsView.as_view(),
        name="empty-trash-chat-sessions",
    ),
    path(
        "sessions/bulk-pin/",
        BulkPinChatSessionsView.as_view(),
        name="bulk-pin-chat-sessions",
    ),
    path(
        "sessions/bulk-archive/",
        BulkArchiveChatSessionsView.as_view(),
        name="bulk-archive-chat-sessions",
    ),
    path(
        "messages/bulk-important/",
        BulkImportantChatMessagesView.as_view(),
        name="bulk-important-chat-messages",
    ),
    path(
        "messages/bulk-delete/",
        BulkDeleteChatMessagesView.as_view(),
        name="bulk-delete-chat-messages",
    ),
    path(
        "sessions/bulk-clear-messages/",
        BulkClearSessionMessagesView.as_view(),
        name="bulk-clear-session-messages",
    ),
    path("messages/copy/", CopyChatMessagesView.as_view(), name="copy-chat-messages"),
    path("sessions/merge/", MergeChatSessionsView.as_view(), name="merge-chat-sessions"),

    path("tags/", ChatSessionTagListCreateView.as_view(), name="chat-session-tags"),
    path("tags/<int:pk>/", ChatSessionTagDetailView.as_view(), name="chat-session-tag-detail"),
    path("tags/<int:tag_id>/sessions/", ChatSessionsByTagView.as_view(), name="sessions-by-tag"),

    path("sessions/<int:pk>/assign-tags/", AssignTagsToChatSessionView.as_view(), name="assign-tags-to-session"),

    path("rag/source-documents/<int:document_id>/", RAGSourceDocumentDetailView.as_view(), name="rag-source-document-detail"),
    path("documents/<int:document_id>/chunks/", DocumentChunksPreviewView.as_view(), name="document-chunks-preview"),
    path("documents/<int:document_id>/rebuild/", RebuildSingleDocumentView.as_view(), name="rebuild-single-document"),
]